# Generated by Django 3.2.8 on 2021-11-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20211103_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
