# Generated by Django 3.2.8 on 2021-11-21 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_portfolio_certificate_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='certificate_link',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
