# Generated by Django 3.2.8 on 2021-11-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20211121_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
