# Generated by Django 3.2.8 on 2021-11-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_portfolio_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='is_featured',
        ),
    ]
