# Generated by Django 3.2.8 on 2021-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_rename_name_certificate_academy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
