# Generated by Django 3.2.8 on 2021-11-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_alter_certificate_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
