# Generated by Django 3.2.8 on 2021-11-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
