# Generated by Django 3.2.8 on 2021-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_remove_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio'),
        ),
    ]
