# Generated by Django 3.2.8 on 2021-11-23 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
