# Generated by Django 3.2.8 on 2021-11-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_alter_media_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
    ]
