# Generated by Django 3.2.8 on 2021-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0030_remove_media_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles'),
        ),
    ]
