# Generated by Django 3.2.8 on 2021-11-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0032_alter_media_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
