# Generated by Django 3.2.8 on 2021-11-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0033_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
